// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func WelcomeBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"container\"><h1>Bienvenido</h1><p>Selecciona una sección para continuar:</p><section><h2>Tarjetas</h2><p><a href=\"/tarjetas\" role=\"button\">Ver todas las tarjetas</a></p><form method=\"get\" action=\"/tarjetas/\"><label for=\"tarjeta-id\">Buscar tarjeta por ID:</label> <input type=\"number\" id=\"tarjeta-id\" name=\"id\" placeholder=\"Ingrese un ID\" min=\"1\" required> <button type=\"submit\">Ir</button></form></section><section><h2>Temas</h2><form method=\"get\" action=\"/temas/\"><label for=\"tema-id\">Buscar tema por ID:</label> <input type=\"number\" id=\"tema-id\" name=\"id\" placeholder=\"Ingrese un ID\" min=\"1\" required> <button type=\"submit\">Ir</button></form></section><section><h2>Usuarios</h2><p><a href=\"/usuarios\" role=\"button\">Ver todos los usuarios</a></p><form method=\"get\" action=\"/usuarios/\"><label for=\"usuario-id\">Buscar usuario por ID:</label> <input type=\"number\" id=\"usuario-id\" name=\"id\" placeholder=\"Ingrese un ID\" min=\"1\" required> <button type=\"submit\">Ir</button></form></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
