// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Tarjetum struct {
	IDTarjeta int32  `json:"id_tarjeta"`
	Pregunta  string `json:"pregunta"`
	Respuesta string `json:"respuesta"`
	OpcionA   string `json:"opcion_a"`
	OpcionB   string `json:"opcion_b"`
	OpcionC   string `json:"opcion_c"`
	IDTema    int32  `json:"id_tema"`
}

type Tema struct {
	IDTema     int32  `json:"id_tema"`
	NombreTema string `json:"nombre_tema"`
}

type Usuario struct {
	IDUsuario     int32  `json:"id_usuario"`
	NombreUsuario string `json:"nombre_usuario"`
	Email         string `json:"email"`
	Contrasena    string `json:"contrasena"`
}
