// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateTarjeta(ctx context.Context, arg CreateTarjetaParams) (Tarjetum, error)
	CreateTema(ctx context.Context, nombreTema string) (Tema, error)
	CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error)
	DeleteTarjeta(ctx context.Context, idTarjeta int32) error
	DeleteTema(ctx context.Context, idTema int32) error
	DeleteUsuario(ctx context.Context, idUsuario int32) error
	GetTarjetaById(ctx context.Context, idTarjeta int32) (Tarjetum, error)
	GetTemaById(ctx context.Context, idTema int32) (Tema, error)
	GetUsuarioById(ctx context.Context, idUsuario int32) (Usuario, error)
	ListTarjetas(ctx context.Context) ([]Tarjetum, error)
	ListTarjetasByTema(ctx context.Context, idTema int32) ([]Tarjetum, error)
	ListTemas(ctx context.Context) ([]Tema, error)
	ListUsuarios(ctx context.Context) ([]Usuario, error)
	UpdateTarjeta(ctx context.Context, arg UpdateTarjetaParams) error
	UpdateTema(ctx context.Context, arg UpdateTemaParams) error
	UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) error
}

var _ Querier = (*Queries)(nil)
